#数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql:///vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
server:
  port: 8081

#开启logging myabtis语句打印
logging:
  level:
    org.javaboy.vhr.mapper: debug

